services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "19000:19000"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    networks:
      - app-network
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt 
    command: ["nginx", "-g", "daemon off;"]

networks:
  app-network:
    driver: bridge
